project:
  type: website
  output-dir: "."
  
website:
  title: "Gustavo Roa"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research & Teaching
      - href: publications.qmd
        text: Publications & Talks
      - href: cv.qmd
        text: CV
        
    right:
      - text: 🌐 Español
        href: ../es/
      - text: 🌐 English
        href: ../en/

lang: en

format:
  html:
    theme:
    css: styles.css
    toc: true

editor: visual

