---
title: "Publications"
format: html
output-file: publications/index.html
---

# 📚 Types

Articles \|  Research Reports \|  Thesis \|  Conferences  \|  Talks

------------------------------------------------------------------------

## Articles

- **Roa, G. A.**, & Ruiz Diaz, D.A. (2025). *Evaluation of tissue phosphorus concentrations as diagnostic tool for phosphorus nutrition in corn.* *Soil Science Society of America Journal*, 89, 70031. <https://doi.org/10.1002/saj2.70031>

- **Roa, G.A.**, Quintana-Obregón, E.A., González-Renteria, M., Ruiz Diaz, D.A. (2024). *Increasing Wheat Protein and Yield through Sulfur Fertilization and Its Relationship with Nitrogen.* *Nitrogen*, 5(3), 553–571. <https://doi.org/10.3390/nitrogen5030037>

------------------------------------------------------------------------

### Dataset

- **Roa, Gustavo**, 2024, "Dataset for meta-analysis on sulfur fertilization effect on wheat protein and yield", <https://doi.org/10.7910/DVN/4RLPP1>, Harvard Dataverse, V4

------------------------------------------------------------------------

### In Progress

- **Roa, G.A.**, Wanithunga, I., de Oliviera, J.B., Rice, C.W., Ruiz Diaz, D.A. (In Preparation, 2025). *Harnessing ¹⁵N Isotopic Tracer Methodology in Agronomy Research: Practical Insights and Case Studies.*
- **Roa, G.A.**, Ruiz Diaz, D.A. (In Preparation, 2025).*Assessing Sulfur Response, Utilization Efficiency, and Diagnostic Tools for Corn.* *Agronomy Journal.*
- **Roa, G.A.**, Hefley, T.J., Vahl, C.I., Ruiz Diaz, D.A. (In Preparation, 2025).*A Practical Approach to Analyzing Long-Term Agricultural Data Using Linear Mixed and Generalized Additive Models.* *Plant Methods.*

------------------------------------------------------------------------

## Research Reports

-   **Roa, Gustavo A.** and Ruiz Diaz, Dorivar A. (2023) "Evaluating the Impact of Long-Term Phosphorus Placement on Corn and Soybean Rotation under Minimum Tillage System," Kansas Agricultural Experiment Station Research Reports: Vol. 9: Iss. 8. <https://doi.org/10.4148/2378-5977.8545>
-   **Roa, Gustavo A.**; Rutter, Edmond B.; and Ruiz Diaz, Dorivar A. (2023) "Evaluation of Plant Tissue Analysis to Assess Phosphorus Nutritional Status for Corn and Soybean," Kansas Agricultural Experiment Station Research Reports: Vol. 9: Iss. 8. <https://doi.org/10.4148/2378-5977.8548>
-   **Roa-Acosta, G. A.** and Ruiz Diaz, D. A. (2022) "Evaluation of Soil Test Phosphorus Extractants and Tissue Analysis for Corn" Kansas Agricultural Experiment Station Research Reports: Vol. 8: Iss. 9. <https://doi.org/10.4148/2378-5977.8347>
-   **Roa-Acosta, G. A.** and Ruiz Diaz, D. A. (2022) "Early-Season Corn Response to Broadcast Pre-Plant Phosphorus Fertilizer Application," Kansas Agricultural Experiment Station Research Reports: Vol. 8: Iss. 9. <https://doi.org/10.4148/2378-5977.8348>

------------------------------------------------------------------------

## Thesis

-   **Roa Acosta, Gustavo A.** 2024. “Evaluating diagnostic tools for phosphorus and sulfur management in corn”. Master of Science, Kansas State University, Manhattan, Kansas.
-   **Roa Acosta, Gustavo A.** 2024. “Application of sulfur in wheat cultivation (Triticum aestivum): its importance for food security” \[Spanish\]. Master’s in Food Security, UnADM, Mexico.
-   **Roa Acosta, G.A.** 2017. “Development of a mobile application (App) for the design and sizing of biodigesters” \[Spanish\]. Graduation Project. EARTH University, Guacimo, Costa Rica.

------------------------------------------------------------------------

## Conference Posters, Presentations & Proceedings

-   Leiva, J.C., **Roa, G.A.** and Ruiz Diaz, D.A. (2024). Efficiency of Different Nitrogen Management Strategies on Winter Wheat Production. 2024 Nitrogen Use Efficiency Workshop. August 2024, University of Illinois Urbana Champaign, IL.
-   **Roa, G.A.** and Ruiz Diaz, D.A. (2024). Enhancing Phosphorus Nutrient Management in Corn Through Tissue Analysis and Diagnostic Tools. ISPA 16th International Conference on Precision Agriculture. July 2024, Manhattan, KS.
-   **Roa, G.A.** and Ruiz Diaz, D.A. (2024). Evaluation of Long-Term Phosphorus Management: An 18-Year Field Study. SSSA Bouyoucos Summer Conference. June 2024, San Juan, Puerto Rico.
-   **Roa, G.A.** and Ruiz Diaz, D.A. (2024). Exploring Long-term Phosphorus Management Strategies for Optimizing Crops Yields in Kansas. Great Plains Soil Fertility Conference. March 2024, Lubbock, TX.
-   **Roa, G.A.** and Ruiz Diaz, D.A. (2023). Assessing Sulfur Response, Utilization Efficiency, and Diagnostic Tools for Corn in Kansas. 53rd North Central Soil Fertility Conference. November 2023, Des Moines, IA.
-   **Roa, G.A.** and Ruiz Diaz, D.A. (2023). Evaluating tissue phosphorus concentration as a diagnostic tool in corn. ASA, CSSA, SSSA International Conference. October 2023, St Lois, MO.
-   Bourns, M.A., Nelson, N.O., **Roa, G.A.** and Ruiz Diaz, D.A. (2023). Sustainable Sufficiency: A New Approach to Phosphorus Fertilizer Management. ASA, CSSA, SSSA International Conference. October 2023, St Lois, MO.
-   **Roa, G.A.**, Rutter, E.B., and Ruiz Diaz, D.A. (2022). Evaluation of Plant Tissue Analysis to Assess Phosphorus Nutritional Status for Corn and Soybean in Kansas. 52nd North Central Soil Fertility Conference. November 2022, Des Moines, IA.
-   **Roa, G.A.** and Ruiz Diaz, D.A. (2022). Corn and Soybean Response to Long-term Phosphorus Placement Under Minimum Tillage System in Kansas. ASA, CSSA, SSSA International Conference. November 2022, Baltimore, MA.
-   **Roa, G.A.** and Ruiz Diaz, D.A. (2022). Corn Yield Response and Evaluation of Soil Test Phosphorus Extractants in Kansas. ASA, CSSA, SSSA International Conference. November 2022, Baltimore, MA. 
-   **Roa, G.A.** and Ruiz Diaz, D. A. (2022). Evaluation of Soil Test Phosphorus Extractants and Tissue Analysis for Corn in Kansas. Great Plains Soil Fertility Conference. March 2022. Virtual.
-   **Roa, G.A.** and Ruiz Diaz, D.A. (2021). Corn response to phosphorus fertilization and evaluation of soil test methods in Kansas soils. 51st North Central Soil Fertility Conference. November 2021, Des Moines, IA.
-   **Roa, G.A.** and Ruiz Diaz, D.A. (2021). Evaluation of Sulfur and Nitrogen Interaction in Winter Wheat Using Different Fertilizer Sources. ASA, CSSA, SSSA International Conference. November 2021, Salt Lake City, UT.
-   **Roa, G.A.** and Ruiz Diaz, D.A. (2021). Early-season corn response to broadcast pre-plant phosphorus fertilizer application in Kansas. ASA, CSSA, SSSA International Conference. November 2021, Salt Lake City, UT.
-   **Roa, G.A.**, Samudio, L.F., Bonini, C.A., and Ruiz Diaz, D.A. (2020). Soil microbial properties with changes in surface soil pH in a long-term no-till system. ASA, CSSA, SSSA International Conference. October 2020, Virtual.

------------------------------------------------------------------------

## Invited Talks

-   **Roa, G.A.** (2024, December 5). Comprehensive soil management: research on fertilization, nutritional diagnostics, and prediction \[Spanish\]. Invited speaker at the World Soil Day Commemoration. Organized by IAAS Paraguay; SOPACIS; Fertimax; and the Faculty of Agricultural Sciences – UNA, San Lorenzo Campus, Paraguay.
