project:
  type: website
  output-dir: _site
  render:
    - index.qmd

website:
  title: "Gustavo Roa"
  navbar:
    left:
      - text: "English"
        href: en/index.qmd
      - text: "Español"
        href: es/index.qmd






