project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - en/*.qmd
    - es/*.qmd

website:
  title: "Gustavo Roa"
  navbar:
    left:
      - text: "English"
        href: en/index.qmd
      - text: "Español"
        href: es/index.qmd


format:
  html:
    toc: true





