project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - en/*.qmd
    - es/*.qmd

website:
  title: "Gustavo Roa"
  navbar:
    left:
      - text: "English"
        href: en/index.qmd
      - text: "Español"
        href: es/index.qmd

format:
  html:
    theme: cosmo
    link-cdn: false   # optional, bundles the CSS locally to avoid the flash of gray




