---
title: ""
format: html
---

# 📚 Tipos

::: {.panel-tabset}

## Artículos
### Revisado por pares

• **Roa, G. A.**, & Ruiz Diaz, D.A. (2025). Evaluación de las concentraciones de fósforo en los tejidos como herramienta diagnóstica para la nutrición de fósforo en el maíz \[Ingles\]. Soil Science Society of America Journal, 89, 70031. <https://doi.org/10.1002/saj2.70031>

• **Roa, G.A.**; Quintana-Obregón, E.A.; González-Renteria, M.; Ruiz Diaz, D.A. Aumento del contenido proteico y rendimiento del trigo mediante fertilización con azufre y su relación con el nitrógeno \[Ingles\]. Nitrogen 2024, 5, 553-571. <https://doi.org/10.3390/nitrogen5030037>

------------------------------------------------------------------------

### Datos

• **Roa, Gustavo**, 2024, "Conjunto de datos para metanálisis sobre el efecto de la fertilización con azufre en la proteína y el rendimiento del trigo" \[Ingles\]. <https://doi.org/10.7910/DVN/4RLPP1>, Harvard Dataverse, V4

------------------------------------------------------------------------

### En Proceso
• **Roa, G.A.** and Ruiz Diaz, D.A. 2025 (Bajo revisión) Evaluación de la respuesta del \[Ingles\]. Agronomy Journal.\
• **Roa, G.A.**, Wanithunga, I., de Oliviera, J. B., Rice, C.W. and Ruiz Diaz, D.A. 2025 (En preparación) Técnicas de marcaje con nitrógeno-15 para la investigación agronómica: Directrices prácticas y estudios de caso \[Ingles\]. Agricultural Systems.\




## Publicaciones de extensión y divulgación
•	Xin, X., Nepal, J., de Oliveira, J., **Roa, G.**, Cominelli, S. y Maryam, H. 2025. “Gestión del nitrógeno del suelo para la productividad y la sostenibilidad: Comprensión de las ganancias y las pérdidas” [Ingles] CSA News, Vol. 70(12), noviembre.
•	Cruz, P., de Oliveira, J., Barra Netto-Ferreira, J., **Roa, G.A.** y Gadhiparti, V. 2025. “Arraigados en la resiliencia: Agricultura regenerativa y el futuro de los sistemas alimentarios” [Ingles] CSA News, Vol. 70(8), agosto.
• **Roa, Gustavo A.** y Ruiz Díaz, Dorivar A. (2023). “Evaluación del impacto de la aplicación de fósforo a largo plazo en la rotación maíz-soja bajo un sistema de labranza mínima.” \[Ingles\] Kansas Agricultural Experiment Station Research Reports: Vol. 9: Iss. 8. <https://doi.org/10.4148/2378-5977.8545>\
• **Roa, Gustavo A.**; Rutter, Edmond B.; y Ruiz Díaz, Dorivar A. (2023). “Evaluación del análisis de tejido vegetal para determinar el estado nutricional de fósforo en maíz y soja.” \[Ingles\] Kansas Agricultural Experiment Station Research Reports: Vol. 9: Iss. 8. <https://doi.org/10.4148/2378-5977.8548>\
• **Roa-Acosta, G. A.** y Ruiz Díaz, D. A. (2022). “Evaluación de métodos de extracción de fósforo en suelos y análisis de tejido vegetal en maíz.” \[Ingles\] Kansas Agricultural Experiment Station Research Reports: Vol. 8: Iss. 9. <https://doi.org/10.4148/2378-5977.8347>\
• **Roa-Acosta, G. A.** y Ruiz Díaz, D. A. (2022). “Respuesta del maíz en etapas tempranas a la aplicación superficial de fertilizante fosfatado antes de la siembra.” \[Ingles\] Kansas Agricultural Experiment Station Research Reports: Vol. 8: Iss. 9. <https://doi.org/10.4148/2378-5977.8348>


## Tesis

• **Roa Acosta, Gustavo A.** 2024. “Evaluación de herramientas diagnósticas para el manejo de fósforo y azufre en maíz.” \[Ingles\] Maestría en Ciencias, Kansas State University, Manhattan, Kansas.\
• **Roa Acosta, Gustavo A.** 2024. “Aplicación de azufre en el cultivo de trigo (Triticum aestivum): su importancia para la seguridad alimentaria.”. Maestría en Seguridad Alimentaria, UnADM, México.\
• **Roa Acosta, G.A.** 2017. “Desarrollo de una aplicación móvil (App) para el diseño y dimensionamiento de biodigestores.”. Proyecto de Graduación, Universidad EARTH, Guácimo, Costa Rica.


## Conferencias
#### Total (17)
•	**Roa, G.A.**, y Ruiz Diaz, D.A. (2025). Nivel crítico de fósforo en el suelo para el cultivo de maíz: Actualizaciones y comparación de métodos en Kansas\[Ingles\]. 55th North Central Soil Fertility Conference. Noviembre de 2025, Des Moines, IA.
•	**Roa, G.A.**, Spooner, J., Hefley, T. y Ruiz Diaz, D.A. (2025). Mejora de los estudios de correlación y calibración de fósforo mediante enfoques bayesianos\[Ingles\]. CANVAS. Noviembre de 2025, Salt Lake City, UT.
•	**Roa, G.A.**, y Ruiz Diaz, D.A. (2025). Perfeccionamiento de las recomendaciones de fósforo en el suelo para el cultivo de maíz en Kansas \[Ingles\]. CANVAS. Noviembre de 2025, Salt Lake City, UT.
• Leiva, J.C., **Roa, G.A.** and Ruiz Diaz, D.A. (2024). Eficiencia de diferentes estrategias de gestión del nitrógeno en la producción de trigo de invierno \[Ingles\]. 2024 Nitrogen Use Efficiency Workshop. Augusto 2024, University of Illinois Urbana Champaign, IL.\
• **Roa, G.A.** and Ruiz Diaz, D.A. (2024). Mejora de la gestión de nutrientes de fósforo en el maíz mediante análisis de tejidos y herramientas de diagnóstico. ISPA 16th International Conference on Precision Agriculture \[Ingles\]. Julio 2024, Manhattan, KS.\
• **Roa, G.A.** and Ruiz Diaz, D.A. (2024). Evaluación de la gestión del fósforo a largo plazo: un estudio de campo de 18 años \[Ingles\]. SSSA Bouyoucos Summer Conference. Junio 2024, San Juan, Puerto Rico.\
• **Roa, G.A.** and Ruiz Diaz, D.A. (2024). Exploración de estrategias de gestión del fósforo a largo plazo para optimizar el rendimiento de los cultivos en Kansas \[Ingles\]. Great Plains Soil Fertility Conference. Marzo 2024, Lubbock, TX.\
• **Roa, G.A.** and Ruiz Diaz, D.A. (2023). Evaluación de la respuesta al azufre, eficiencia de utilización y herramientas de diagnóstico para el maíz en Kansas \[Ingles\]. 53rd North Central Soil Fertility Conference. Noviembre 2023, Des Moines, IA.\
• **Roa, G.A.** and Ruiz Diaz, D.A. (2023). Evaluación de la concentración de fósforo tisular como herramienta diagnóstica en maíz \[Ingles\]. ASA, CSSA, SSSA International Conference. Octubre 2023, St Lois, MO.\
• Bourns, M.A., Nelson, N.O., **Roa, G.A.** and Ruiz Diaz, D.A. (2023). Suficiencia sostenible: Un nuevo enfoque para la gestión de fertilizantes fosfatados \[Ingles\]. ASA, CSSA, SSSA International Conference. Octubre 2023, St Lois, MO.\
• **Roa, G.A.**, Rutter, E.B., and Ruiz Diaz, D.A. (2022). Evaluación del análisis de tejido vegetal para evaluar el estado nutricional del fósforo en maíz y soja en Kansas \[Ingles\]. 52nd North Central Soil Fertility Conference. Noviembre 2022, Des Moines, IA.\
• **Roa, G.A.** and Ruiz Diaz, D.A. (2022). Respuesta del maíz y la soja a la aplicación de fósforo a largo plazo en sistemas de labranza mínima en Kansas \[Ingles\]. ASA, CSSA, SSSA International Conference. Noviembre 2022, Baltimore, MA.\
• **Roa, G.A.** and Ruiz Diaz, D.A. (2022). Respuesta del rendimiento del maíz y evaluación de los extractantes de fósforo en análisis de suelo en Kansas \[Ingles\]. ASA, CSSA, SSSA International Conference. Noviembre 2022, Baltimore, MA.\
• **Roa, G.A.** and Ruiz Diaz, D. A. (2022). Evaluación de extractantes de fósforo en suelos y análisis de tejidos para maíz en Kansas \[Ingles\]. Great Plains Soil Fertility Conference. Marzo 2022. Virtual.\
• **Roa, G.A.** and Ruiz Diaz, D.A. (2021). Respuesta del maíz a la fertilización con fósforo y evaluación de los métodos de análisis de suelos en suelos de Kansas \[Ingles\]. 51st North Central Soil Fertility Conference. Noviembre 2021, Des Moines, IA.\
• **Roa, G.A.** and Ruiz Diaz, D.A. (2021). Evaluación de la interacción de azufre y nitrógeno en el trigo de invierno utilizando diferentes fuentes de fertilizantes \[Ingles\]. ASA, CSSA, SSSA International Conference. Noviembre 2021, Salt Lake City, UT.\
• **Roa, G.A.** and Ruiz Diaz, D.A. (2021). Respuesta del maíz de temporada temprana a la aplicación de fertilizantes de fósforo antes de la siembra en Kansas \[Ingles\]. ASA, CSSA, SSSA International Conference. Noviembre 2021, Salt Lake City, UT.\
• **Roa, G.A.**, Samudio, L.F., Bonini, C.A., and Ruiz Diaz, D.A. (2020). Propiedades microbianas del suelo con cambios en el pH de la superficie del suelo en un sistema de labranza cero a largo plazo \[Ingles\]. ASA, CSSA, SSSA International Conference. Octubre 2020, Virtual.


## Charlas

• **Roa, G.A.** (2024, diciembre 5). Gestión integral de suelos: investigación en fertilización, diagnóstico nutricional y predicción. Orador invitado en la Conmemoración del Día Mundial del Suelo. Organizado por IAAS Paraguay; SOPACIS; Fertimax; and Facultad de Ciencias Agrarias - UNA, Campus San Lorenzo, Paraguay.

:::