---
title: ""
format: html
---

## Recursos Digitales

¡Bienvenido a la sección de Recursos! Aquí encontrarás enlaces a mis herramientas interactivas, conjuntos de datos de acceso abierto y materiales descargables.

### Aplicaciones Shiny

Interfaces web desarrolladas para apoyar la toma de decisiones en fertilidad de suelos y manejo de nutrientes.

- **[FertRecKS](https://gustavo-roa.shinyapps.io/KS-Fertilizer-Recommendation-App-R/)** – Herramienta de Recomendación de Fertilizantes para Kansas

### Harvard Dataverse

Accede a conjuntos de datos abiertos asociados a mis publicaciones.

- **[Meta-análisis de la Fertilización con Azufre en Trigo](https://doi.org/10.7910/DVN/4RLPP1)**

### Zedono 

- **[XRD-Soil-Mineral-ID](https://zenodo.org/records/15882594)** – Una herramienta para la identificación semicuantitativa de minerales del suelo utilizando datos de XRD

### Repositorios GitHub

Código fuente que respalda mi trabajo.

- **[Gustavo-Roa](https://github.com/Gustavo-Roa)**

### Materiales

Recursos descargables
