on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      # Render the root index page for redirect
      - name: Render root index
        run: quarto render index.qmd

      # Render the English sub-project
      - name: Render English site
        run: quarto render en/

      # Render the Spanish sub-project
      - name: Render Spanish site
        run: quarto render es/

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          # We already rendered the site, so skip re-rendering during publish
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}